

<p><img alt="logo.fua" height="100px" src='https://drive.google.com/uc?export=view&id=1s0UktWjCsp8F6Q6EmCjfofwVYH_1tWVE' align="left" hspace="10px" vspace="5px"></p>




<h1><center><font size="6px"> <strong>INTRODUCCIÓN A PANDAS </font> </strong></center></h1>

#<center> <font size="4.5" >**FACULTAD DE CIENCIAS Y HUMANIDADES**<center>

# **¿Qué es Numpy?**

Es un paquete para *computación científica* en Python que proporciona la capacidad para trabajar con arreglos multidimensionales y varios objetos derivados (matrices por ejemplo). Esta librería incluye una gran variedad de rutinas para operaciones rápidas en arreglos entre las que se destacan:

* manipulación matemática, lógica y de formas, 
* clasificación y selección,
* transformación discreta de Fourier,
* álgebra lineal básica, 
* operaciones estadísticas básicas, simulación aleatoria y mucho más.

Para mayor información se puede consultar el tutorial de [NumpY](https://numpy.org/doc/1.20/numpy-user.pdf)

In [ ]:
#importando la librería
import numpy as np # import (paquete) as (alias)

In [ ]:
np. #¿Que contiene Numpy?

Un **array** es una estructura de datos de un mismo tipo organizada en forma de tabla o cuadrícula de distintas dimensiones.

<img src="https://drive.google.com/uc?id=1TJ7ScqEezKMKi5o8lQ1icHc6KizVbNzc" width="600px" height="350">
</center>




In [ ]:
A= np.arange(-1,10,2) #Un primer arreglo
A.shape

(6,)

In [ ]:
A = np.arange(-1,10,2) #Cuando se asigna un valor, el resultado no se imprime.
A 

array([-1,  1,  3,  5,  7,  9])

In [ ]:
B = A.reshape(2,3) #Para cambiar la forma del arreglo de tal forma que tenga 2 filas y 3 columnas
B

array([[-1,  1,  3],
       [ 5,  7,  9]])

In [ ]:
b = np.array([[0,1,2,3],[4,5,6,7],[4,5,6,7]])    # Creación de un array de rango 2
print(b)
print(b.shape)                     # Impresión de las dimensiones "(2, 4)"

[[0 1 2 3]
 [4 5 6 7]
 [4 5 6 7]]
(3, 4)


In [ ]:
a = np.zeros((2,2))                        # Creación de un array de zeros
print("Array de ceros", a)                 # Imprime "[[ 0.  0.]
                                           #          [ 0.  0.]]"

b = np.ones((1,2))                         # Creación de un array de unos
print("Arrays de unos", b)                 # Imprime "[[ 1.  1.]]"

c = np.full((2,2), 8)                      # Creación de un array de una costante
print("Array constante", c)                # Imprime "[[ 8.  8.]
                                           #          [ 8.  8.]]"

d = np.eye(2)                              # Creación de la matriz indentidad de 2x2.
print("Matriz identidad 2x2", d)           # Imprime "[[ 1.  0.]
                                           #          [ 0.  1.]]"

e = np.arange(0, 20, 2)                    # Creación de un vector lleno de una secuencia lineal
print("Array de una secuencia lineal" ,e)  # que comience en 0, finalice en 18, con paso 2.


f = np.linspace(0, 1, 5)                   # Crea un vector de cinco valores espaciados 
print("Array de una secuencia lineal2",f)  # uniformemente entre 0 y 1.   


g = np.random.random((2,2))                # Creación de una matriz de 2x2 de valores aleatorios.
print("Array de números aleatorios(u)", g) # distribuidos uniformemente.


h = np.random.normal(0, 1, (3, 3))         # Creación una matriz 3x3 de valores aleatorios normalmente 
print("Array de números aleatorios(n)", h) # distribuidos con media 0 y desviación estándar 1.


i = np.random.randint(0, 10, (3, 3))       # Creación de una matriz 3x3 de números enteros aleatorios
print("Array de números aleatorios(i)",i)  # en el intervalo [0,10)


Array de ceros [[0. 0.]
 [0. 0.]]
Arrays de unos [[1. 1.]]
Array constante [[8 8]
 [8 8]]
Matriz identidad 2x2 [[1. 0.]
 [0. 1.]]
Array de una secuencia lineal [ 0  2  4  6  8 10 12 14 16 18]
Array de una secuencia lineal2 [0.   0.25 0.5  0.75 1.  ]
Array de números aleatorios(u) [[0.51989479 0.97598464]
 [0.27627394 0.13487288]]
Array de números aleatorios(n) [[ 1.07703738  0.38255813 -1.8279359 ]
 [-1.61604915 -0.54775481 -1.19038275]
 [-2.64572272 -0.45233585 -0.8473888 ]]
Array de números aleatorios(i) [[7 4 9]
 [0 4 7]
 [3 6 9]]


# **Atributos**

Cada array tiene como atributos: <code>ndim</code>  (el número de dimensiones), <code>shape</code> (el tamaño de cada dimensión) y <code>size</code> (el tamaño total de la matriz o número de elementos)

In [ ]:
x1 = np.random.randint(10, size=6)          # array unidimensional
x2 = np.random.randint(10, size=(3, 4))     # array bidimensional
x3 = np.random.randint(10, size=(3, 4, 5))  # array tridimensional

print(x3)
print("ndim: ", x3.ndim)
print("shape:", x3.shape)
print("size: ", x3.size,"\n")

[[[1 1 1 3 8]
  [6 6 5 8 6]
  [4 1 4 8 6]
  [0 1 8 0 1]]

 [[0 3 9 9 5]
  [1 6 7 0 1]
  [2 4 6 2 1]
  [0 0 8 2 4]]

 [[5 0 0 0 5]
  [0 1 0 3 5]
  [4 6 8 2 6]
  [8 5 7 3 4]]]
ndim:  3
shape: (3, 4, 5)
size:  60 



## **Indexado**



Al igual que en las librerias estándar de Python, se puede acceder a la i-ésima componente de un array especificando el índice deseado entre []

In [ ]:
x1

array([8, 8, 1, 9, 7, 4])

In [ ]:

print(x1[3])

9


In [ ]:
#caso tridimensional
x3

array([[[1, 1, 1, 3, 8],
        [6, 6, 5, 8, 6],
        [4, 1, 4, 8, 6],
        [0, 1, 8, 0, 1]],

       [[0, 3, 9, 9, 5],
        [1, 6, 7, 0, 1],
        [2, 4, 6, 2, 1],
        [0, 0, 8, 2, 4]],

       [[5, 0, 0, 0, 5],
        [0, 1, 0, 3, 5],
        [4, 6, 8, 2, 6],
        [8, 5, 7, 3, 4]]])

In [ ]:
x3[1,1,1]

6

In [ ]:
print("Dos formas de acceder al mismo elemento: \n")
print("x3[1][1][0] =", x3[1][1][0])
print("x3[1,1,0] =", x3[1,1,0])

Dos formas de acceder al mismo elemento: 

x3[1][1][0] = 8
x3[1,1,0] = 8


# **Segmentación**

La sintaxis de segmentación NumPy sigue la de la lista estándar de Python: <code>x[inicio:final:paso]</code>

In [ ]:
x = np.arange(10) 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
x[5::-2]

array([5, 3, 1])

In [ ]:
x3

array([[[1, 1, 1, 3, 8],
        [6, 6, 5, 8, 6],
        [4, 1, 4, 8, 6],
        [0, 1, 8, 0, 1]],

       [[0, 3, 9, 9, 5],
        [1, 6, 7, 0, 1],
        [2, 4, 6, 2, 1],
        [0, 0, 8, 2, 4]],

       [[5, 0, 0, 0, 5],
        [0, 1, 0, 3, 5],
        [4, 6, 8, 2, 6],
        [8, 5, 7, 3, 4]]])

In [ ]:
print(x3)
#Hasta el 2do array, dos filas y dos columnas'
x3[:2,:2,:2]

[[[1 1 1 3 8]
  [6 6 5 8 6]
  [4 1 4 8 6]
  [0 1 8 0 1]]

 [[0 3 9 9 5]
  [1 6 7 0 1]
  [2 4 6 2 1]
  [0 0 8 2 4]]

 [[5 0 0 0 5]
  [0 1 0 3 5]
  [4 6 8 2 6]
  [8 5 7 3 4]]]


array([[[1, 1],
        [6, 6]],

       [[0, 3],
        [1, 6]]])

*A* veces es útil copiar explícitamente los datos dentro de un array o un  subarray. Esto se puede hacer más fácilmente con el
método <code>copy()</code>

In [ ]:
x2

array([[7, 9, 6, 1],
       [0, 7, 4, 8],
       [8, 5, 7, 3]])

In [ ]:
cop =x2[:2,1].copy()
cop

array([9, 7])

# **Reshape**



Otro tipo útil de operación es el "reshape" de arrays. 

In [ ]:
grilla = np.arange(1, 10)
grilla

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grilla.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
newarr.shape

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


(2, 3, 2)

# **Operaciones entre arrays** 


**Operaciones vectorizadas**

El cálculo con arrays en NumPy puede ser muy rápido o muy lento. La clave para hacerlo rápido es usar operaciones *vectorizadas*, generalmente implementadas a través de las funciones universales de NumPy (ufuncs)

In [ ]:
x = np.linspace(0, 1, 5)
x  

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
y = np.linspace(1, 2, 5)  
y

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
x/y

array([0.        , 0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
x = np.arange(1,5)
print(x)

# Operadores aritméticos
print('x+2 = ',np.add(x,2))
print('x-2 =',np.subtract(x,2))
print('-x =',np.negative(x))
print('x*2 =',np.multiply(x,2))
print('x/2 =',np.divide(x,2))
print('x^2 =',np.power(x,2))

[1 2 3 4]
x+2 =  [3 4 5 6]
x-2 = [-1  0  1  2]
-x = [-1 -2 -3 -4]
x*2 = [2 4 6 8]
x/2 = [0.5 1.  1.5 2. ]
x^2 = [ 1  4  9 16]


In [ ]:
# Funciones trigonométricas
theta = np.linspace(0,np.pi,3)

print('sin(theta) =',np.sin(theta))
print('cos(theta) =',np.cos(theta))



sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
# Exponenciales y logaritmos
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

e^x = [ 2.71828183  7.3890561  20.08553692 54.59815003]
2^x = [ 2.  4.  8. 16.]
3^x = [ 3  9 27 81]
ln(x) = [0.         0.69314718 1.09861229 1.38629436]
log2(x) = [0.        1.        1.5849625 2.       ]
log10(x) = [0.         0.30103    0.47712125 0.60205999]


## **Operaciones Básicas.**

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Suma elemento a elemento
print(x + y)
print(np.add(x, y))

# Resta elemento a elemento.
print(x - y)
print(np.subtract(x, y))

# Multiplicación elemento a elemento.
print(x * y)
print(np.multiply(x, y))

# División elemento a elemento.
print(x / y)
print(np.divide(x, y))

# Raiz cuadrada a cada elmento.
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
print("Suma total de los elementos del array", np.sum(x))  # Calculo de la suma de todos los elementos.
print("Suma de cada columna",np.sum(x, axis=0))  # Suma de cada columna
print("Suma de cada fila",np.sum(x, axis=1))  # Suma de cada fila

Suma total de los elementos del array 10
Suma de cada columna [4 6]
Suma de cada fila [3 7]


Para más funciones puede consultar [este enlace](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

#### <center> **TABLA DE FUNCIONES BÁSICAS** </center>

|    Función  | Operador |      
|:---------------:|:--------:|
|  Valor absoluto |    np.abs()    | 
|  Exponencial    |     np.exp()   | 
| Logaritmo natural   |     np.log()    |     
|       seno      |     np.sin()    | 
|      coseno      |     np.cos()   | 
|       tangente      |     np.tan()    | 
|     arcoseno      |     np.arcsin()    |
|      arcocoseno      |     np.arccos()    |
|       arcotangente    |    np.arctan()    |


